{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Seu Carlos Users API",
    "description": "An API that handles user's CRUD requests for Seu Carlos's project",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "host": "localhost:5000",
  "basePath": "/api",
  "tags": [
    {
      "name": "Users",
      "description": "API for users in the system"
    }
  ],
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/signup": {
      "post": {
        "tags": ["Users"],
        "description": "Create new user in system",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "description": "User that we want to create",
            "schema": {
              "$ref": "#/definitions/UserPost"
            }
          }
        ],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "New user is created",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["Users"],
        "summary": "Get all users in system",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Users"
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "parameters": [
        {
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "ID of user that we want to find",
          "type": "string"
        }
      ],
      "get": {
        "tags": ["Users"],
        "summary": "Get user with given ID",
        "responses": {
          "200": {
            "description": "User is found",
            "schema": {
              "$ref": "#/definitions/UserGet"
            }
          }
        }
      },
      "delete": {
        "summary": "Delete user with given ID",
        "tags": ["Users"],
        "responses": {
          "204": {
            "description": "User is deleted"
          }
        }
      },
      "put": {
        "summary": "Update user with give ID",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "description": "User with new values of properties",
            "schema": {
              "$ref": "#/definitions/UserUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User is updated",
            "schema": {
              "$ref": "#/definitions/UserGetUpdated"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "UserPost": {
      "required": ["email", "name", "phone", "password"],
      "properties": {
        "name": {
          "type": "string",
          "uniqueItems": true
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "example": {
        "name": "Raniel Sobrinho",
        "email": "raniel.example@mail.com",
        "phone": "23 988888888",
        "password": "1234567890"
      }
    },
    "UserUpdate": {
      "required": ["email", "name", "phone", "password"],
      "properties": {
        "name": {
          "type": "string",
          "uniqueItems": true
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "example": {
        "name": "Raniel Sobrinho 2",
        "email": "raniel.update@mail.com",
        "phone": "23 988888888",
        "password": "1234567890"
      }
    },
    "UserGetUpdated": {
      "properties": {
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string",
          "uniqueItems": true
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        }
      },
      "example": {
        "id": 1,
        "name": "Raniel Sobrinho 2",
        "email": "raniel.update@mail.com",
        "phone": "23 988888888",
        "created_at": "2025-02-19T15:52:59.931Z"
      }
    },
    "UserGet": {
      "properties": {
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string",
          "uniqueItems": true
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        }
      },
      "example": {
        "id": 1,
        "name": "Raniel Sobrinho",
        "email": "raniel.example@mail.com",
        "phone": "23 988888888",
        "created_at": "2025-02-19T15:52:59.931Z"
      }
    },
    "Users": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/UserGet"
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      },
      "example": {
        "token": "jlkjldslkfhsalf123298afjNÃ‡cascnalsdkj-aZ"
      }
    }
  }
}
